# Generated by Django 5.1.7 on 2025-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0002_reports_uploads_delete_uploadedfile_reports_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='file_data',
        ),
        migrations.AddField(
            model_name='uploads',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
