# Generated by Django 5.1.6 on 2026-01-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0003_remove_uploads_file_data_uploads_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='current_version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='eda.uploads')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/versions/')),
                ('version_number', models.IntegerField()),
                ('action_taken', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='eda.uploads')),
            ],
            options={
                'db_table': 'dataset_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
